server:
  port: ${PORT:80}
  https: ${SSL_SERVER:false}
  compression:
    enabled: true
  cors:
    origins: ${CORS_ORIGINS:*}
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:postgres}
    username: ${PG_LOGIN:postgres}
    password: ${PG_PASS:postgres}
    schema: ${PG_SCHEMA:public}
  # JPA / HIBERNATE
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      id:
        new_generator_mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
